### ISSUE TITLE
labels not readable in input

### ISSUE THREAD

**Issue by ggwzrd** [Official-Codaisseur-Graduate/my-imp-trainer#13]
![Screenshot 2019-12-05 at 10 03 16](https://user-images.githubusercontent.com/17532350/70220277-9e58f100-1746-11ea-9a69-e34e21c5fd3a.png)

**Comment by mbosselut** [comment]
Labels now readable when field is active

**Comment by ggwzrd** [comment]
but not in the default state, please fix that

**Comment by mbosselut** [comment]
Done
