### ISSUE TITLE
Use icons and text instead of cards

### ISSUE THREAD

**Issue by ggwzrd** [Official-Codaisseur-Graduate/my-imp-trainer#15]
![Screenshot 2019-12-05 at 10 20 29](https://user-images.githubusercontent.com/17532350/70221581-eaa53080-1748-11ea-9b5c-ac3e7022e484.png)

![3](https://user-images.githubusercontent.com/17532350/70221610-f8f34c80-1748-11ea-8804-efcb8d8ffcbb.png)

**Comment by mbosselut** [comment]
Done, added icons for kcal, time and workouts completed
