### ISSUE TITLE
Remove border from profile image and name and add it only to image 

### ISSUE THREAD

**Issue by ggwzrd** [Official-Codaisseur-Graduate/my-imp-trainer#16]
![Screenshot 2019-12-05 at 10 23 31](https://user-images.githubusercontent.com/17532350/70221886-6acb9600-1749-11ea-8761-d9f83a142e30.png)
![Screenshot 2019-12-05 at 10 25 26](https://user-images.githubusercontent.com/17532350/70221990-9189cc80-1749-11ea-9f5d-b80a1a9e8e9f.png)

**Comment by mbosselut** [comment]
Done through the User component and styles.js
