### ISSUE TITLE
Add illustrations and improve alignments

### ISSUE THREAD

**Issue by ggwzrd** [Official-Codaisseur-Graduate/my-imp-trainer#17]
![Screenshot 2019-12-05 at 10 22 20](https://user-images.githubusercontent.com/17532350/70222205-f80eea80-1749-11ea-81fc-82054782f1a0.png)

This part has to updated to be more appealing. You should use a mixed grid alignment like in the design below:

![Screenshot 2019-12-05 at 10 22 14](https://user-images.githubusercontent.com/17532350/70222196-f2190980-1749-11ea-8e69-81517b9dfc4f.png)

Additionally, let's add some illustrations to the left Paper at the bottom like the following: https://www.freepik.com/free-vector/happy-character-winning-prize-with-flat-design_2773855.htm#page=1&query=victory&position=1

**Comment by mbosselut** [comment]
Switched to mixed grid and added illustration to streak container

**Comment by ggwzrd** [comment]
@mbosselut I don't see this enhancement in `development`

**Comment by mbosselut** [comment]
Should be visible now !
