### ISSUE TITLE
Cannot access workouts from Calendar

### ISSUE THREAD

**Issue by ggwzrd** [Official-Codaisseur-Graduate/my-imp-trainer#18]
![Screenshot 2019-12-05 at 10 38 23](https://user-images.githubusercontent.com/17532350/70223123-728c3a00-174b-11ea-8301-1f856b06cf67.png)

**Comment by hakan-kemal** [comment]
Workout name in calendar links to workout id.

**Comment by apavlushina** [comment]
now it works - I have created separate component for it
