### ISSUE TITLE
Continue to today's workout doesn't not do anything

### ISSUE THREAD

**Issue by ggwzrd** [Official-Codaisseur-Graduate/my-imp-trainer#19]
![Screenshot 2019-12-05 at 10 39 49](https://user-images.githubusercontent.com/17532350/70223225-9f405180-174b-11ea-8250-db21b6ec8bb5.png)

**Comment by apavlushina** [comment]
It links for workout page - for me it works, should it do something else?

**Comment by ggwzrd** [comment]
I see, only the link works. Could the whole card be clickable? @apavlushina

**Comment by apavlushina** [comment]
sure, will fix it!

**Comment by mbosselut** [comment]
Done by Hakan
