### ISSUE TITLE
Page transition snaps both mobile and desktop

### ISSUE THREAD

**Issue by ggwzrd** [Official-Codaisseur-Graduate/my-imp-trainer#20]
[Screen Recording 2019-12-05 at 10.52.01.zip](https://github.com/Official-Codaisseur-Graduate/my-imp-trainer/files/3926133/Screen.Recording.2019-12-05.at.10.52.01.zip)

**Comment by ghost** [comment]
working on it

**Comment by ghost** [comment]
transition works on routing between components, Please check and let me know if ok

**Comment by ggwzrd** [comment]
<img width="422" alt="Screenshot 2019-12-06 at 10 05 30" src="https://user-images.githubusercontent.com/17532350/70310448-f60f5f00-180f-11ea-9ecd-9bd32c7335ae.png">


Still not readable when an input has value.

**Comment by ghost** [comment]
I think it's not related to this (transition) issue, no?
