### ISSUE TITLE
Workout page (MOBILE) updates

### ISSUE THREAD

**Issue by ggwzrd** [Official-Codaisseur-Graduate/my-imp-trainer#36]
Remove the IMPT TRAINER logo and move the title in the card I mention after the design 👇. The image should be positioned on the top of the page without any border like in the following design:

![2](https://user-images.githubusercontent.com/17532350/70258368-6aa0ba00-178c-11ea-9947-58b241b5085f.png)

add a floating card as shown above ☝️ where you can display the details of the workout. Please use a border-radius of 16px for top-right and top-left borders, while the bottom ones should have 0 radius.

the card should be scrollable and the button "Finish" should be floating over the text.

## THIS DESIGN SHOULD BE IMPLEMENTED ONLY FOR MOBILE

use [Hidden](https://material-ui.com/components/hidden/) component from MUI to hide the floating card component in desktop.

Comments on the desktop design will be communicated in another issue.

**Comment by ghost** [comment]
**Update**

Hi Giulio, I have added a component and made as much as possible similar to the example here, to be hidden on a desktop is not applied **yet** but it's designed to be for mobile.
